### ISSUE TITLE
Wrong reason ("for benchmarking") asked for writing

### ISSUE THREAD

**Issue by scop** [MartinBriza/MediaWriter#119]
When mediawriter asks for permission to write to a USB stick, it asks for authentication, but says the reason is wrong: it says "for benchmarking". This is on Fedora 25, mediawriter 4.1.0.

![auth-wrong-reason](https://user-images.githubusercontent.com/109152/30293402-0a06f8e8-9742-11e7-8777-492aced77979.png)

**Comment by MartinBriza** [comment]
Yes, I know. That's sorta intentional and will get "fixed" once UDisks2 starts shipping a method that supports consecutive writing and then reading from the same drive with one call. 
I'm using OpenForBenchmark because if I used OpenForRestore and then OpenForBackup, polkit would ask for your password again after a long writing process.
