### ISSUE TITLE
No translation support

### ISSUE THREAD

**Issue by piotrdrag** [MartinBriza/MediaWriter#14]
There is no translation support, making the app unusable for the majority of Fedora users. Ideally, it would be integrated with <https://fedora.zanata.org/>, although adding the gettext infrastructure is the first step.

Additional question: is https://github.com/lmacken/liveusb-creator a dead project? Should I remove it from Zanata (<https://fedora.zanata.org/project/view/liveusb-creator>), so no more translators' time is wasted on it?

**Comment by MartinBriza** [comment]
I'm going to add translation support soon. Most of the text in the app is from the websites though so there won't be much to translate directly for FMW. 

Regarding lmacken's repo, I'm still not sure what to do with it. I'll probably revert it to its original state before I started contributing because back then, it had a whole different set of features than it does now. I'll let you know after I will have talked to Luke about it to see what he thinks.

**Comment by MartinBriza** [comment]
Fixed with cf330b07d6f248e38f7758f3ea69475374664815

**Comment by piotrdrag** [comment]
Any chance you could use Fedora's Zanata instance instead of the generic one? It's a Fedora-specific project, and https://fedora.zanata.org/ is beneficial to us in many ways (more focus, more translators...).

Also a note on Zanata: "Version" is actually used for branches, not release versions.

**Comment by MartinBriza** [comment]
I'll take a look at this tomorrow. Nobody has contributed yet so using the Fedora instance is no problem. Also thanks for the information about the versioning. I admit it confused me a bit.

**Comment by MartinBriza** [comment]
I moved the project to the Fedora Zanata instance and have updated the configs and README.

**Comment by piotrdrag** [comment]
Thanks, looks great! I added it to the appropriate group. You should start receiving translations soon.
