### ISSUE TITLE
Crash on Windows 10 (Build 17063)

### ISSUE THREAD

**Issue by keltor** [MartinBriza/MediaWriter#146]
Here's the Windows event for the fault:

Faulting application name: mediawriter.exe, version: 0.0.0.0, time stamp: 0x00000000
Faulting module name: ntdll.dll, version: 10.0.17063.1000, time stamp: 0x2b661a7c
Exception code: 0xc0000005
Fault offset: 0x0003f0f9
Faulting process id: 0x37f4
Faulting application start time: 0x01d38205086d8d0f
Faulting application path: C:\Program Files (x86)\Fedora Media Writer\mediawriter.exe
Faulting module path: C:\WINDOWS\SYSTEM32\ntdll.dll
Report Id: ab21d8d6-a192-42b0-bf6f-581fd7ee4c52
Faulting package full name: 
Faulting package-relative application ID: 

This was using 4.1.0 which is obviously the current @ https://getfedora.org/en/workstation/download/.

I downloaded the 4.1.1 build and it worked perfectly.  I'm a little confused as it looks like the differences were for the flatpak build and one of the docs.  Maybe a build environment change?

**Comment by MartinBriza** [comment]
There is actually a pretty big difference between 4.1.0 and 4.1.1, especially for Windows users. The new version doesn't use graphics acceleration, which is what prevents most of the crashes user experienced in the past - which is probably your case, too. Since you say it's fixed for you with 4.1.1, I'll close this issue. However, please feel free to come back with any question or issue you may encounter in the future.
