### ISSUE TITLE
ArchLinux32

### ISSUE THREAD

**Issue by kenny-wettlaufer** [MartinBriza/MediaWriter#150]
Hey, I noticed your AUR package for mediawriter no longer supports i686 & figured you may have decided to stop supporting it in your AUR package because Arch Linux dropped support for it, well now we have an unofficial Arch Linux 32-bit community & ISO, so there are Arch users who still use 32-bit, I don't know if you want to keep maintaining 32-bit for your AUR package but I just figured I'd let you know that 32-bit users still exist! Thanks!

**Comment by MartinBriza** [comment]
Hi. Sorry, I'm not the maintainer of the AUR package. Personally I don't see any issue with having a 32b version of FMW so please check with the maintainer here: https://aur.archlinux.org/packages/mediawriter/ .
From the look of the PKGBUILD script it seems he forgot to add the 32b architecture since the start so there doesn't seem to be any technical reason to not include that. :)
