### ISSUE TITLE
Windows does not recognize LiveUSB drive.

### ISSUE THREAD

**Issue by Krantz-XRF** [MartinBriza/MediaWriter#158]
The storage of my USB drive is large, and I want to make full use of space. 
It seems that after creating the LiveUSB, without deleting the image from my drive I cannot use the rest space. Windows just don't recognize the partition. On Fedora, however, I can see the available space on that drive and save files into it. 
For some reason I would like to keep this image on my USB drive, is it possible to both keep the image and make use of the rest space on my drive (on Windows of course)?

**Comment by ousia** [comment]
I’m afraid the USB drive has a filesystem that cannot be written to.

![iso-fmw](https://user-images.githubusercontent.com/203767/38745377-a54969d0-3f44-11e8-9b03-695c1fdb2a3e.png)

I wonder how you are able to write data to that USB drive in _Fedora_.

**Comment by MartinBriza** [comment]
@Krantz-XRF Sorry for not getting in touch sooner, I've probably missed the notification.
You cannot use the rest of the space due to how the partition format works with Fedora images - it's specially tuned to work right when booting from CD, on Macs and regular PCs, therefore not all partitions are visible from all systems. 

It's not possible, at this moment, to use the remaining space, I'm sorry.
