### ISSUE TITLE
font.pixelSize harmful on my 4k display

### ISSUE THREAD

**Issue by yaneti** [MartinBriza/MediaWriter#34]
I just tried mediawriter on rawhide on my 4k 28" display  3840x2160 and it has tiny, tiny text in a small window.

Just for a experiment I went and removed all the explicit font.PIxelSize calls in the qml code (all of them, no matter what pixel size). The result is a much more bareable experience.

I don't know much about qt or how removing the explicit sizes might affect other platforms but I think generally leaving the font size on the mercy of  the desktop environment is the preferrable way to go here.
Perhaps styling some of the captions as "heading", "h2" or something of the sort...

**Comment by MartinBriza** [comment]
Actually this is the better way to do it. Except I had to disable high DPI scaling because it is broken on X11 clients. If you experience issues with the size of the tool, you can set the QT_AUTO_SCREEN_SCALE_FACTOR to 1 (or "true"? Qt docs aren't very clear on this). This should scale the whole UI 2x. I'm intending to enable this behavior by default when Qt will have fixed their highDPI support on Linux.

**Comment by yaneti** [comment]
Oh well, agree to disagree then :).  Considering the lack of complexity in the mediawriter UI I really think absolute sizing makes no sense.  The only fixed things currently seem to be the png logos, but those I'll assume could be replaced with svg-s

**Comment by MartinBriza** [comment]
Well, I'll at least try (on Windows though, I don't have access to a Linux hidpi system) how well it fares with pointsize instead of pixelsize and come back to you with what I found.

To explain why I use pixelSize: if you open main.qml, there is the "$" function which is used to scale everything in the UI by any arbitrary factor. I presumed there would be a way to get the actual factor from the system. However, there is no reliable way of doing so independently of the platform in Qt as of now. Just guessing the scaling factor from the DPI of the screen is not enough (broken EDIDs, different user settings, etc).

**Comment by AdamWill** [comment]
I have a hidpi laptop running Fedora and can test changes for you, @MartinBriza . I have to agree with @yaneti , though: *please* don't pixel size things. Please allow the desktops to do their job and scale your interface. hidpi displays are only getting more common.

**Comment by MartinBriza** [comment]
Fonts will now be bigger
UI will be a bit broken, yet usable.

**Comment by yaneti** [comment]
Thanks for the attempt but it doesn't help here, everything is still small.
To give you an example of what helps the first screen to look normal in my setup.
```
diff --git a/app/components/DelegateImage.qml b/app/components/DelegateImage.qml
index b7c1197..dc91ce4 100644
--- a/app/components/DelegateImage.qml
+++ b/app/components/DelegateImage.qml
@@ -80,14 +80,12 @@ Item {
             Text {
                 Layout.fillWidth: true
                 verticalAlignment: Text.AlignBottom
-                font.pointSize: $(9)
                 text: release.name
                 color: palette.text
             }
             Text {
                 Layout.fillWidth: true
                 verticalAlignment: Text.AlignTop
-                font.pointSize: $(9)
                 text: release.summary
                 wrapMode: Text.Wrap
                 color: "#a1a1a1"
```

**Comment by MartinBriza** [comment]
Well, I can't do that, for obvious reasons. Can you please specify which environment are you running in and how have you set up the font sizes or scaling?
