### ISSUE TITLE
be more clear about resetting usb sticks

### ISSUE THREAD

**Issue by kparal** [MartinBriza/MediaWriter#55]
We talked about this recently. Windows and Mac usually can't reformat sticks containing Fedora images using internal tools. FMW can reset those sticks, but it's not very well announced. We should inform the user better.

I imagine we could do it like this:
* Keep the top floating bar when Fedora-formatted stick is plugged in, that's great.
* Include `Reset stick` button on the main screen. Open up a dialog that will show available drives to reset, and starts resetting process after confirmation.
* When an image is successfully written, instead of just saying `Writing has been finished`, also include something like `When you want to reset your stick back to an empty drive, choose "Reset" in the main screen`.

That should make it clear enough that users can use FMW to reset their stick back.

**Comment by MartinBriza** [comment]
Thank you.
For points 1 and 3, yes. I have implemented that a minute ago and will push it soon, along with an update to 4.0.8 when I have tested it.
For point 2, jimmac wouldn't be happy :( I'll ping him to see what we can do about this feature. He's generally really strongly against including any more buttons or information inside the window. 
I'm planning a slight overhaul for 4.1 so I hope we'll have some mockups ready by then too.
Otherwise, there will be the top bar when you start FMW and there's a flash drive already present - or it will present the bar when you connect a new restoreable drive while it is running and the writing dialog is not open. This could suffice - but again, I'll consult that.

**Comment by kparal** [comment]
I understand, but I'm trying to cover the use case when the user blindly confirms the "writing done" dialog without really reading it. Then it's obvious if you see "Reset" button on the main screen, but you have no way of figuring that out without it (why would you ever run FMW again? It will not cross users' minds). If jimmac has suggestions how to cover this without using a button, sure :-) But I think this use case should not be disregarded.

**Comment by MartinBriza** [comment]
Well, the message about FMW being able to restore the drive is displayed
right after you start writing the image - I think this is noticeable
enough.
Actually, the notification bar was his idea and thinking about it, you
don't really need anything else. Maybe the logic behind showing and hiding
it could be done in a different way though - now for example when you have
the writing dialog open, the notification won't pop out.

2017-01-09 19:48 GMT+01:00 Kamil Páral <notifications@github.com>:

**Comment by kparal** [comment]
If the bar pops out when you finish writing (I haven't tested this), it's true that that could be obvious enough.

**Comment by MartinBriza** [comment]
The bar doesn't pop out after you've finished writing, it doesn't seem right to me.
What does happen is the message inside the writing progress box.

**Comment by MartinBriza** [comment]
>Keep the top floating bar when Fedora-formatted stick is plugged in, that's great.
Kept the top floating bar there
>Include Reset stick button on the main screen. Open up a dialog that will show available drives to reset, and starts resetting process after confirmation.
After a discussion with jimmac, I think this won't be necessary. Displaying just one drive for resetting is completely fine for almost all use cases.
>When an image is successfully written, instead of just saying Writing has been finished, also include something like When you want to reset your stick back to an empty drive, choose "Reset" in the main screen.
The message will now say "Your computer will now report this drive is much smaller than it really is. Just insert your drive again while Fedora Media Writer is running and you'll be able to restore it back to its full size."

From my point of view, the list of problems from this issue is resolved now, therefore I'll close this issue. However, feel free to disagree or add more points to it by either reopening the issue or creating a new one.

Thanks for the hints.
