### ISSUE TITLE
helper/linux/writejob.cpp: 3 * bad delete ?

### ISSUE THREAD

**Issue by dcb314** [MartinBriza/MediaWriter#76]
helper/linux/writejob.cpp:223]: (error) Mismatching allocation and deallocation: unalignedBuffer
helper/linux/writejob.cpp:231]: (error) Mismatching allocation and deallocation: unalignedBuffer
helper/linux/writejob.cpp:239]: (error) Mismatching allocation and deallocation: unalignedBuffer

new [] needs delete [].

**Comment by squimrel** [comment]
#75

**Comment by MartinBriza** [comment]
You need the buffer to be page-aligned on Linux (and it's simpler to keep it that way for all three platforms as long as it's possible to do it) because it's required for UDisks2's OpenForBenchmark to work.

Regarding this bug, thanks for the report, it's going to get fixed soon, either by me or by @squimrel 's PR.

**Comment by MartinBriza** [comment]
Closed by #75
